# Copyright (c) Dynamic Quants and affiliates.
#
# This source code is part of Quantix library and is licensed under the MIT
# license found in the LICENSE file in the root directory of this source tree.

"""TimescaleDB connection client."""

import os

import psycopg2
from dotenv import load_dotenv

# Get the environment variables from the .env file (or .env.test).
load_dotenv()


class TimescaleClient:
    """TimescaleDB connection client using psycopg2 library."""

    def __init__(self):
        host = os.environ.get("TIMESCALEDB_HOST")
        user = os.environ.get("TIMESCALEDB_USER")
        password = os.environ.get("TIMESCALEDB_PASSWORD")
        db = os.environ.get("TIMESCALEDB_DB")
        port = os.environ.get("TIMESCALEDB_PORT")

        # Create the connection string with the environment variables.
        self._connection_string = f"postgresql://{user}:{password}@{host}:{port}/{db}"

    def connect(self):
        """
        Connect to the TimescaleDB database using the connection string generated by
        the environment variables.
        """
        return psycopg2.connect(self._connection_string)
