[tool.coverage.run]
branch = true
source = ["core"]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report term --cov-report html:'../../coverage/packages/core/html' --cov-report xml:'../../coverage/packages/core/coverage.xml' --html='../../reports/packages/core/unittests/html/index.html' --junitxml='../../reports/packages/core/unittests/junit.xml'"

[tool.poetry]
name = "core"
version = "1.0.0"
description = "Provides all abstractions and utilities for algorithm trading."
authors = ["Dynamic Quants"]
license = "MIT"
readme = "README.md"

[[tool.poetry.packages]]
include = "core"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
