# Copyright (c) Dynamic Quants and affiliates.
#
# This source code is part of Quantix library and is licensed under the MIT
# license found in the LICENSE file in the root directory of this source tree.

"""TimescaleDB connection client."""

import os

import psycopg2
from dotenv import load_dotenv

# Get the environment variables from the .env file (or .env.test).
load_dotenv()


class TimescaleClient:
    """TimescaleDB connection client using psycopg2 library."""

    def __init__(self, schema: str = "public") -> None:
        host = os.environ.get("TIMESCALEDB_HOST")
        port = os.environ.get("TIMESCALEDB_PORT")
        db = os.environ.get("TIMESCALEDB_DB")
        user = os.environ.get("TIMESCALEDB_USER")
        password = os.environ.get("TIMESCALEDB_PASSWORD")

        # Check if the environment variables are set.
        if not all([host, port, db, user, password]):
            raise ValueError("Missing TimescaleDB environment variables.")

        connection_string = f"""
            host={host}
            port={port}
            dbname={db}
            user={user}
            password={password}
        """

        options = f"-c search_path={schema}"

        self._conn = psycopg2.connect(connection_string, options=options)

    def connect(self) -> psycopg2.extensions.connection:
        """
        Connect to the TimescaleDB database using the connection string generated by
        the environment variables.
        """

        return self._conn
